name: orderbike
channels:
  - conda-forge
dependencies:
  - pre-commit>=3.6.2
  - pytest>=8.0.2
  - osmnx>=1.9.1
  - tqdm>=4.66.2
  - ipykernel>=6.29.3
  - haversine>=2.8.1
  - momepy>=0.7.0
  - python-igraph>=0.11.8
  - scipy>=1.16.0
  - scikit-learn>=1.7.1
  - pip
  - pip:
      - urbantoygraph
      - opencv-python>=4.9.0
